---
title: "visualizeData"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{visualizeData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(FinalProject)
```


```{r}
  library(ggplot2)
  library(fiftystater)

createMap <- function (df, var, scale_title, plot_title){
  low_color='gray100' 
  high_color="gray0"
  scale_title = scale_title
  num_vec<-eval(substitute(var),df)

  map1 <- ggplot(df, aes(map_id = StateName)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = num_vec), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_fill_continuous(low = low_color, high= high_color, guide = guide_colorbar(title = scale_title)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "right", panel.background = element_blank()) +
  ggtitle(plot_title)
  
}
  
createMap(StateVsAvgCost, averageCost, "Test", "Test2")->map_test

map_test

  low_color='gray100' 
  high_color="gray0"
  scale_title = 'Average total cost'

  map1 <- ggplot(StateVsAvgCost, aes(map_id = StateName)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = averageCost), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_fill_continuous(low = low_color, high= high_color, guide = guide_colorbar(title = scale_title)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "right", panel.background = element_blank()) +
  ggtitle('Average cost of hospital procedures by state')
  
  map1
  
  low_color2='gray100' 
  high_color2="gray0"
  scale_title2 = 'Number of heart transplants'

  map2 <- ggplot(StateVsNumHeartTransplants, aes(map_id = StateName)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = numberOfDischarges), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_fill_continuous(low = low_color2, high= high_color2, guide = guide_colorbar(title = scale_title2)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "right", panel.background = element_blank()) +
  ggtitle('Number of Heart Transplants by State', subtitle = 'To visualize the frequency of the most expensive procedure.')
  
  map2
  
  
  low_color3='gray100' 
  high_color3="gray0"
  scale_title3 = 'Number of procedures'

  map3 <- ggplot(StateVsNumProcedures, aes(map_id = StateName)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = numberOfDischarges), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_fill_continuous(low = low_color2, high= high_color2, guide = guide_colorbar(title = scale_title2)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "right", panel.background = element_blank()) +
  ggtitle('Number of Procedures by State')
  
  map3
    
```